// Короткие названия для карточек каталога (≤ ~34 знаков — одна строка в карточке 300 px).
// Полное название остаётся на странице товара. Убираем то, что уже сказано в русском описании,
// и «хвосты» вроде Moisturizing / Refreshing / Pack.
export const titles = {
  "cosrx-good-morning-gel": "COSRX Good Morning Gel Cleanser",
  "banila-clean-it-zero": "Banila Co Clean It Zero Original",
  "boj-green-plum-cleanser": "Beauty of Joseon Green Plum",
  "round-lab-dokdo-balm": "Round Lab 1025 Dokdo Balm",
  "anua-pore-cleansing-oil": "Anua Heartleaf Pore Control Oil",
  "somebymi-miracle-foam": "Some By Mi AHA BHA PHA Miracle Foam",
  "purito-deep-sea-oil": "Purito From Green Cleansing Oil",
  "drg-green-pore-balm": "Dr.G Green Deep Pore Balm",
  "beplain-mung-bean-foam": "Beplain Mung Bean Foam",
  "abib-heartleaf-pad": "Abib Heartleaf Pad Clear Touch",
  "boj-green-plum-toner": "Beauty of Joseon Green Plum Toner",
  "cosrx-aha-bha-toner": "COSRX AHA/BHA Clarifying Toner",
  "isntree-hyaluronic-toner": "Isntree Hyaluronic Acid Toner",
  "numbuzin-no5-pad": "Numbuzin No.5 Vitamin Pad",
  "skinfood-carrot-pad": "Skinfood Carrot Carotene Pad",
  "tonymoly-mochi-toner": "Tony Moly Ceramide Mochi Toner",
  "boj-glow-serum": "Beauty of Joseon Glow Serum",
  "numbuzin-no3-serum": "Numbuzin No.3 Serum",
  "purito-centella-serum": "Purito Wonder Releaf Centella",
  "anua-azelaic-serum": "Anua Azelaic Acid 10 Serum",
  "anua-niacinamide-txa-serum": "Anua Niacinamide 10% + TXA 4%",
  "anua-pdrn-capsule-serum": "Anua PDRN Capsule 100 Serum",
  "anua-vita-10-serum": "Anua Vita 10 Porestrix Serum",
  "banila-propolis-ampoule": "Banila Co Propolis Ampoule",
  "cosrx-alpha-arbutin": "COSRX Alpha-Arbutin 2 Serum",
  "cosrx-snail-96": "COSRX Snail 96 Mucin Essence",
  "numbuzin-no5-glutathione": "Numbuzin No.5 Glutathione Serum",
  "skin1004-tone-brightening": "SKIN1004 Tone Brightening Ampoule",
  "skin1004-centella-ampoule": "SKIN1004 Centella Ampoule",
  "manyo-bifida-ampoule": "Manyo Bifida Biome Ampoule",
  "medicube-kojic-serum": "Medicube Kojic Acid Turmeric Serum",
  "axis-y-dark-spot-serum": "AXIS-Y Dark Spot Glow Serum",
  "celimax-retinal-shot": "celimax Retinal Shot Booster",
  "abib-pdrn-cream": "Abib PDRN Intensive Cream",
  "anua-pdrn-cream": "Anua PDRN Hyaluronic Acid Cream",
  "anua-peach-77-cream": "Anua Peach 77 Niacin Cream",
  "boj-red-bean-gel": "Beauty of Joseon Red Bean Gel",
  "wishtrend-bakuchiol-cream": "By Wishtrend Bakuchiol Night Cream",
  "cosrx-ceramide-cream": "COSRX The Ceramide Moisturizer",
  "centellian-madeca-cream": "Centellian24 Madeca Cream",
  "illiyoon-hyaluronic-cream": "Illiyoon Hyaluronic Cream",
  "laneige-water-bank-cream": "Laneige Water Bank Blue Cream",
  "medipeel-peptide-9-cream": "Medi-Peel Peptide 9 Tox Cream",
  "round-lab-birch-cream": "Round Lab Birch Juice Cream",
  "skin1004-centella-cream": "SKIN1004 Centella Cream",
  "s-nature-squalane-cream": "S.Nature Aqua Squalane Cream",
  "torriden-dive-in-cream": "Torriden Dive-In Cream",
  "vely-vely-spicule-cream": "Vely Vely Spicule 1200 Cream",
  "wellage-hyaluronic-cream": "Wellage Real Hyaluronic Cream",
  "celimax-dual-barrier-cream": "celimax Dual Barrier Cream",
  "manyo-bifida-cream": "Manyo Bifida Biome Cream",
  "anua-heartleaf-sun-cream": "Anua Heartleaf Silky Sun Cream",
  "anua-peach-tone-up": "Anua Peach UV Tone Up",
  "biodance-collagen-mask": "Biodance Bio-Collagen Mask",
  "drjart-cryo-rubber-mask": "Dr.Jart+ Cryo Rubber Mask",
  "jmsolution-pearl-mask": "JMsolution Marine Pearl Mask",
  "petitfee-black-pearl-mask": "Petitfee Black Pearl & Gold Mask",
  "koelf-royal-jelly-mask": "Koelf Gold & Royal Jelly Mask",
  "koelf-ruby-rose-mask": "Koelf Ruby & Bulgarian Rose Mask",
  "boj-red-bean-pore-mask": "Beauty of Joseon Red Bean Mask",
  "cosrx-pdrn-overnight-mask": "COSRX PDRN Exosome Glaze Mask",
  "medicube-collagen-glow-mask": "Medicube Collagen Milky Glow Mask",
  "medicube-collagen-overnight-mask": "Medicube Collagen Overnight Mask",
  "medicube-kojic-mask": "Medicube Kojic Acid Turmeric Mask",
  "medicube-pdrn-caffeine-mask": "Medicube PDRN Caffeine Mask",
  "abib-mild-acidic-mask": "Abib Heartleaf Fit Sheet Mask",
  "anua-heartleaf-sheet-mask": "Anua Heartleaf 77% Sheet Mask",
  "boj-calming-barrier-mask": "Beauty of Joseon Centella Mask",
  "mediheal-nmf-ampoule-mask": "Mediheal N.M.F Aquaring Mask",
  "nature-republic-olive-mask": "Nature Republic Olive Mask",
  "round-lab-birch-mask": "Round Lab Birch Juice Mask",
  "round-lab-dokdo-mask": "Round Lab 1025 Dokdo Mask",
  "torriden-dive-in-mask": "Torriden Dive-In Mask",
  "heimish-eye-patch": "Heimish Bulgarian Rose Eye Patch",
  "petitfee-agave-patch": "Petitfee Agave Cooling Eye Mask",
  "round-lab-birch-pad": "Round Lab Birch Juice Pad",
};
